### ISSUE TITLE
Setup is giving Error

### ISSUE THREAD

**Issue by hmqq** [hexhex/hexlite-owlapi-plugin#3]
I am trying to setup the hexlite-owlapi-plugin and i am getting the following error.
![hexlitw-OWLApi-Error](https://user-images.githubusercontent.com/45597150/129564737-ea589ee2-b51c-4a9f-b535-bf9ff8293d23.JPG)

Kindly help me in the setup of this plugin.

Kind Regards,
Haya

**Comment by peschue** [comment]
Hello Haya,

In https://github.com/hexhex/hexlite-owlapi-plugin/blob/master/setup_and_test_within_conda.py please find the lines

```
	# for public access
	#HEXLITE_CLONE_SOURCE='https://github.com/hexhex/hexlite.git'
	# for developer access (including push possibility)
	HEXLITE_CLONE_SOURCE='git@github.com:hexhex/hexlite.git'
```

And swap the comment so that the first HEXLITE_CLONE_SOURCE is active but the second one is not.

**Comment by hmqq** [comment]
It worked. Thankyou!
