### ISSUE TITLE
Plugin give error

### ISSUE THREAD

**Issue by hmqq** [hexhex/hexlite-owlapi-plugin#4]
I have setup the hexlite and the owlapi plugin for hexlite. The predefined tests "setup_and_test_within_conda.py" worked fine. The problem is how to use this plugin with hexlite? because if I give a command like this "hexlite querykoala1.hex --pluginpath /home/user/hexlite/plugins/ --plugin javaapiplugin at.ac.tuwien.kr.hexlite.OWLAPIPlugin" it gave me this error: "E:   main.py:140:For reporting bugs, unexpected behavior, or suggestions, please report an issue here: https://github.com/hexhex/hexlite/issues". Maybe i am doing something wrong. But hexlite does not find the owl-api plugin.

Kind Regards,
Haya

**Comment by peschue** [comment]
Hello Haya,

1) Please try to set the CLASSPATH environment variable. Usually it already contains some value required for Java, but you need to add more values (they are separated by a colon symbol ":").

2) Did you enter the conda environment?

For 2), please use the name you used for setup_and_test_with_conda.py and do

```
conda activate <name>
```

For 1) then please try with 
```
CLASSPATH=$CLASSPATH:plugin/target/owlapiplugin-1.1.0.jar:plugin/target/classes/:plugin/ hexlite querykoala1.hex --pluginpath /home/user/hexlite/plugins/ --plugin javaapiplugin at.ac.tuwien.kr.hexlite.OWLAPIPlugin
```
From the root directory of the hexlite repository where `setup_and_test_within_conda.py` worked before.

**Comment by hmqq** [comment]
I have followed the instructions but it still seemed not to work.  When i executed "setup_and_test_with_conda.py" it created a hexlite folder in the plugin directory.  From there i try to use the javaapilugin. I have attached the hexlite-owlapi-plugin-1.2 directory and the error that i am getting.
![structure](https://user-images.githubusercontent.com/45597150/129694253-55aab95e-ad94-4181-bc2f-9954b20c1f10.JPG)

![hexliteError](https://user-images.githubusercontent.com/45597150/129695270-fc71234c-aae6-4b5f-9797-ad1d3745cb84.JPG)

**Comment by peschue** [comment]
Please check if you find the following JAR file in the hexlite installation:

java-api/target/hexlite-java-plugin-api-1.4.0.jar

It needs to be part of the CLASSPATH (it contains the IPluginAtom).

**Comment by hmqq** [comment]
Now i think it start working but it is giving me now an error that there is no file named koala-meta.json. But this file exists in the example directory.
![hexJSONerror](https://user-images.githubusercontent.com/45597150/129708271-0062d87c-c20a-49ae-9047-fbc160de7fe0.JPG)

**Comment by peschue** [comment]
I am glad that it works a bit now. Are you sure that you are executing with the right working directory?

If you need to change the path to koala-meta.json you can do that in the first line of https://github.com/hexhex/hexlite-owlapi-plugin/blob/master/examples/koala/querykoala1.hex or https://github.com/hexhex/hexlite-owlapi-plugin/blob/master/examples/koala/querykoala2.hex

I think the test script executes within the examples/koala directory. If you execute in the root directory, please add 'examples/koala/' before the `koala-meta.json` in the `.hex` file and it should load.

Thank you for your patience!

**Comment by hmqq** [comment]
You are right. it is working from 'examples/koala/'. 
![WokingHexLiteOWLApi](https://user-images.githubusercontent.com/45597150/129719691-bc86b40a-652a-4221-9582-d44d55b78be0.JPG)

Thankyou for the help :)
