### ISSUE TITLE
rules+ontology

### ISSUE THREAD

**Issue by hmqq** [hexhex/hexlite-owlapi-plugin#5]
I want to query a hybrid knowledge base using HEXlite. For Instance In my ontology i have a class named GoldenEagle and it has an instance Harry. My rules file has one rules which state that Tim is also an instance of GoldenEagle.

When I execute this `instances(A) :- &dlCro[onto,"ont:GoldenEagle"](A).` It only show me the ontology instances and give me error for the rule part.

My question is how can I make this "instances(A)" rule to read instances of "GoldenEagle" from both ontology and rule file in HEXLite?

**Comment by peschue** [comment]
I am not sure what you mean by "rules file". You will have one ontology file (that can maybe import others) and one HEX source file. &dlCro is the "read only concept" atom, it will return true for all A that are in the ont:GoldenEagle concept in the unmodified (that means read only) ontology. the &dlC atom can query the ontology after modification. Currently most documentation is in source code and in the examples, but if you have a concrete question I can help you.

**Comment by peschue** [comment]
can you show the error you receive for the rule part?

**Comment by hmqq** [comment]
Basically, I don't have any instance of EndangeredSpecies in ontology but I added a fact in my hex file that contains GoldenEagle an instance of EndangeredSpecies. Now I want to query both the ontology and (rule)hex file to give me instances of EndamgeredSpecies wherever they are mentioned. It then checks the ontology part which contains nothing but the hex file contain one fact. I want it to return me that (fact)instance of EndangeredSpecies. I don't want to add this fact into the ontology. I hope the explanation is clear enough that what I am trying to do with hexlite-owl-api. I have attached a zip file that contains the ontology and the hex file. It is doing what I have explained above (getting no error anymore) but I am not sure that is the right way to do it. Also because of less documentation support it is hard to figure out what actually I can do with available predicates/ what information I can put in these.  
[try.zip](https://github.com/hexhex/hexlite-owlapi-plugin/files/7160020/try.zip)

Also, could you kindly tell me is there also a possibility to add just a class name (without individual) or refer to disjoint classes/properties in this plugin?

**Comment by peschue** [comment]
I am unfortunately very low on time these days, but you will need to create a "delta" predicate that represents how you want to change the ontology.

See the example file https://github.com/hexhex/hexlite-owlapi-plugin/blob/master/examples/koala/querykoala2.hex
Here `delta(qalt,addc("koala:TasmanianDevil",A))` means that the modification named `qalt` has the concept assertion `A : koala:TasmanianDevil` added for all substitiutions of `A`.

YOu query ontological reasoning under a modification as follows (same example):

`&dlC[onto,delta,qalt,"koala:Animal"](A)`

which is a predicate that is true for all instances that are classified as `koala:Animal` in ontology `onto` under modification `delta(qalt,...)`.

I hope this helps a bit.
