### ISSUE TITLE
Add instance 

### ISSUE THREAD

**Issue by hmqq** [hexhex/hexlite-owlapi-plugin#7]
How can i add instances to a specific class in ontology through HEX atoms?

**Comment by peschue** [comment]
Please see example https://github.com/hexhex/hexlite-owlapi-plugin/blob/master/examples/koala/querykoala2.hex

For example, `delta(qalt,addc("koala:TasmanianDevil","foo"))` will assert that instance "foo" is added to class (addc) "koala:TasmanianDevil" in the ontology modification that is selected with constant "qalt".

So `&dlC[onto,delta,qalt,"koala:Animal"](A)` will see such changes, while `&dlC[onto,delta,hwalt,"koala:Animal"](A)` will not see the "qalt" changes but the changes selected by constant "hwalt".

The theory behind is explained in

Peter Schüller:
A new OWLAPI interface for HEX-programs applied to explaining contingencies in production planning. NeHuAI@ECAI 2020: 25-31
http://ceur-ws.org/Vol-2659/schueller.pdf
