### ISSUE TITLE
Use hexlite-owlapi-plugin with DLVHEX2

### ISSUE THREAD

**Issue by hmqq** [hexhex/hexlite-owlapi-plugin#8]
Hi,

Is it possible to use dlv for grounding and solving instead of clingo with hexlite?

**Comment by peschue** [comment]
DLVHEX2 is a different software than Hexlite, and DLVHEX2 also uses clingo internally.

As for your intended question: unfortunatley this is not possible.

Firstly, the plugin is based on the Java API of Hexlite and DLVHEX2 has no Java API.

Secondly, clingo is tightly integrated with Hexlite for efficient solving and currently there are no resources to integrate IDLV/WASP into Hexlite. It was initially planned, but for now it is not realistic.
